# Generated by Django 4.1.3 on 2023-01-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sell', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.devices')),
            ],
        ),
    ]
