# Generated by Django 4.1.3 on 2023-01-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_alter_devices_status_sells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
    ]
